### PR TITLE
Create share button

### LINKED ISSUE #149: Create share button that share the best score to social media on home page
We should enhance the social experience for this project since all the games are single-player games. 

We should allow users to share their best scores more easily, by doing that, we could add a button on the home page to allow users to share their scores on social media. (e.g. Twitter, Reddit)

### PR DESCRIPTION
**Pull request by lche262**
## Todo
- [x] Added a share button in best game modal
- [x] Added a corresponding button for sharing it to different social media
- [x] Create the correct sharing link on each website

## Motivation

The player should allow themselves to share their best scores on social media.

## Summary of changes

-Added a new button on the best score modal
-Added a new modal to hold the social media buttons

## Attached GitHub issue

Closes #149

### Local Build
- [x] Ran all local tests `npm run test:ci`
- [x] Manually tested my solution

### GitHub
- [x] Target branch has been set correctly
- [x] PR has been rebased onto target branch
- [x] PR has been assigned an owner
- [x] Author has performed a self-review of the code

### CODE REVIEW

**Comment by hmin697** [comment]
I have test runned the version, it awkwardly places game icon in best games modal.
image
It would be good if you could fix it

**Comment by lche262** [comment]
> I have test runned the version, it awkwardly places game icon in best games modal. image It would be good if you could fix it

The game icon was added after I added the button and I was not aware until it was merged. I will fix it now!

**Comment by lche262** [comment]
> I have test runned the version, it awkwardly places game icon in best games modal. image It would be good if you could fix it

image
it is now fixed!

**Comment by Zasheus** [comment]
Great job! However, the Facebook share button doesn't seem to put the score in the textbox to post.

**Comment by lche262** [comment]
> 

That is because the share function of FaceBook is not allowing us to put any text in it. Sadly we can only post links on Facebook.

**Review by Zasheus — APPROVED** [review]
Awesome looks good to me!

**Pull request merged**
